### ISSUE TITLE
Email address of the author 

### ISSUE THREAD

**Issue by sanshibayuan** [wukaoliu/CVPR2020-HAttMatting#1]
how to contact the author for the dataset? I cannot find an email address in the repo. Also the paper has not been released...

**Comment by yuhaoliu7456** [comment]
The dataset will open to the public as soon as possible.




            
            
                
                    
                            
                                
                            
                            
                                yuhao liu
                            
                    
                        
                            
                                    邮箱：yuhaoliu7456@gmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 04/25/2020 10:46, Zhiyin Hong wrote: 
how to contact the author for the dataset? I cannot find an email address in the repo. Also the paper has not been released...

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wukaoliu/CVPR2020-HAttMatting/issues/1",
"url": "https://github.com/wukaoliu/CVPR2020-HAttMatting/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sankexin** [comment]
> how to contact the author for the dataset? I cannot find an email address in the repo. Also the paper has not been released...

@sanshibayuan 
Have you received the dataset? Can you send me a copy? I can't reach the author.
sankexinfeiji@163.com

**Comment by John-Yao** [comment]
@sankexin  Could you apply for dataset by the email

**Comment by newjavaer** [comment]
@sankexin Have you received the dataset? Can you send me a copy? I can't reach the author. litoxx@2019.cqut.edu.cn

**Comment by shkarupa-alex** [comment]
@wukaoliu , i wrote you an email. Could you please respond?

**Comment by luoww1992** [comment]
> 该数据集将尽快向公众开放。yuhao liu邮箱：yuhaoliu7456@gmail.com签名由网易邮件管理员定制。2020年4月25日10：46，Hong Zhiyin Hong写道：如何联系作者获取数据集？我在回购中找不到电子邮件地址。此外，该论文尚未发布... —之所以收到此邮件，是因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。[{“ @context ”：“ http://schema.org ”，“ @type ”：“ EmailMessage”，“ potentialAction”：{“ @type ”：“ ViewAction”，“ target”：“[](https://github.com/wukaoliu/CVPR2020-HAttMatting/issues/1)[](https://github.com/wukaoliu/CVPR2020-HAttMatting/issues/1)“，” name“：”查看问题“}，”描述“：”在GitHub上查看此问题“，”发布者“：{” @type “：”组织“，” name“：” GitHub“，” url“： “ https://github.com ”}}]

i can't find the email here, so can you share the link to me in  my email - luoww1992@sina.com ?
