### ISSUE TITLE
when the dataset will be published?

### ISSUE THREAD

**Issue by sangenan** [wukaoliu/CVPR2020-HAttMatting#6]
Thank you for your work. It’s great. I would like to ask when the dataset will be published. I have sent an email request, but I have not received any reply.

**Comment by yuhaoliu7456** [comment]
Thanks for your attention, our dataset has been published a while ago. I
guess your email was positioned in the trash. Maybe you can send it again.

Big Totoro <notifications@github.com> 于2020年7月6日周一 上午10:03写道：

**Comment by uptodiff** [comment]
> Thanks for your attention, our dataset has been published a while ago. I guess your email was positioned in the trash. Maybe you can send it again.


“has been published”？，I could not find the download link of the dataset.

**Comment by yuhaoliu7456** [comment]
We'll not open the dataset link to the public directly. If anyone else
needs this dataset for non-commercial uses, please let us know and send us
an email to access it.

uptodiff <notifications@github.com> 于2020年7月6日周一 下午2:55写道：

**Comment by 99991** [comment]
I contacted the authors by e-mail and received a link to the dataset and can confirm that the alpha mattes are of very high quality.

The subjects are mostly people, glass and furry animals, therefore this dataset will definitely be useful to evaluate the performance of alpha matting methods on tasks which also come up in the real world.

The test dataset does not contain trimaps, so we should probably come up with an agreeable method to generate them from the alpha mattes in a reproducible way since small differences in trimaps can have a big influence on alpha matting quality.
The dilation + erosion method described in Deep Image Matting is very slow, but almost the same results can be achieved by thresholding distance fields. One such implementation can be found in the code released by @poppinace in his IndexNet matting repository: https://github.com/poppinace/indexnet_matting/blob/6f3a04dc082e9969137f315d57dd9e9259cd56ad/scripts/hldataset.py#L201

I still have a question about the license:

Are there any restrictions on distributing the weights of a neural network that has been trained on this dataset? In order to promote reproducibility in academic research, it would be desirable to be able to distribute pretrained models such that everyone can verify any performance claims.

**Comment by luoww1992** [comment]
> Thank you for your work. It’s great. I would like to ask when the dataset will be published. I have sent an email request, but I have not received any reply.

have you got the dataset lnk ?  i can't find author‘s email. Can you share the dataset to me ? thanks!

**Comment by sangenan** [comment]
I didn't get the data set

**Comment by luoww1992** [comment]
@wukaoliu , i can't find the email. Can you share the dataset to me ? thanks!
