### ISSUE TITLE
How does the model know which is the foreground without trimap?

### ISSUE THREAD

**Issue by universewill** [wukaoliu/CVPR2020-HAttMatting#8]
I notice that the HAttMatting model doesn't need Trimap. So, how does it know which is the foreground if there is a dog and a person in one image?

**Comment by bluesky314** [comment]
I am guessing it will fail in most cases as the datasets they trained is very limited and mostly humans. But author may have better response after his/her testing

**Comment by AntiCherryPicking** [comment]
> I notice that the HAttMatting model doesn't need Trimap. So, how does it know which is the foreground if there is a dog and a person in one image?

HAHA, the following answer is absolutely right! The model's learning ability is limited! This paper is full of cherry-picking and untruthful results!
I prefer this work as an extension about the "portrait segmentation" task rather than matting, in other words, "matting without trimap" is now a nonsense！

**Comment by javiermachinelearning** [comment]
@AntiCherryPicking , could you elaborate more please, they say that their results are better than late fusion and just slightly worse than context aware matting; I am actually trying to decide between using something like HattMatting and trimap-using models like FBA and GCA, any tips are very welcome :)
